### PR TITLE
Switched to net45 and to latest Stylecop 6.1.0

### PR DESCRIPTION
**Pull request by gpailler**
I updated .net target framework from 3.5 to 4.5 and Stylecop from 4.7.51 to latest 6.1.0

Thanks for the project.

### CODE REVIEW

**Comment by BrunoJuchli** [comment]
@gpailler Bonsoir
Thanks!
Have you done any additional testing / smoke testing? (Just so I know how much I got to test myself ;-) ).
I'll review and merge changes in the next few days. If I fail to give feedback until Tuesday, 15th October, please ping me.

**Comment by gpailler** [comment]
Well I integrated the updated version in an existing project and it's working fine but I haven't done much manual tests. My tests were limited to VS with Resharper and Continuous Integration (msbuild).

**Comment by BrunoJuchli** [comment]
@gpailler 
I changed to .net Framework 4.0 instead of 4.5 - because StyleCop 6.1 is also targeting 4.0.
I released 6.1.40-pre (not sure if increasing the version to 6.1 is a good idea, but also doubt that it matters that much...).
Could you give it a try? Thanks.

**Comment by gpailler** [comment]
Hi @BrunoJuchli 
Whoa! What a big version jump ! 😃 

I tested the new Nuget package on our project and it's working fine. Perfect!

**Pull request merged**
